/*
 * This file is generated by jOOQ.
*/
package com.mp.model.jooq.tables.records;


import com.mp.model.jooq.tables.SysAuthentication;
import com.mp.model.jooq.tables.interfaces.ISysAuthentication;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAuthenticationRecord extends UpdatableRecordImpl<SysAuthenticationRecord> implements Record3<Integer, String, String>, ISysAuthentication {

    private static final long serialVersionUID = -25917307;

    /**
     * Setter for <code>testdb.sys_authentication.auth_id</code>.
     */
    @Override
    public void setAuthId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb.sys_authentication.auth_id</code>.
     */
    @Override
    public Integer getAuthId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>testdb.sys_authentication.auth_code</code>.
     */
    @Override
    public void setAuthCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb.sys_authentication.auth_code</code>.
     */
    @Override
    public String getAuthCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>testdb.sys_authentication.password</code>.
     */
    @Override
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>testdb.sys_authentication.password</code>.
     */
    @Override
    public String getPassword() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SysAuthentication.SYS_AUTHENTICATION.AUTH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysAuthentication.SYS_AUTHENTICATION.AUTH_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysAuthentication.SYS_AUTHENTICATION.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getAuthId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAuthenticationRecord value1(Integer value) {
        setAuthId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAuthenticationRecord value2(String value) {
        setAuthCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAuthenticationRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAuthenticationRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISysAuthentication from) {
        setAuthId(from.getAuthId());
        setAuthCode(from.getAuthCode());
        setPassword(from.getPassword());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISysAuthentication> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysAuthenticationRecord
     */
    public SysAuthenticationRecord() {
        super(SysAuthentication.SYS_AUTHENTICATION);
    }

    /**
     * Create a detached, initialised SysAuthenticationRecord
     */
    public SysAuthenticationRecord(Integer authId, String authCode, String password) {
        super(SysAuthentication.SYS_AUTHENTICATION);

        set(0, authId);
        set(1, authCode);
        set(2, password);
    }
}
