/*
 * This file is generated by jOOQ.
*/
package com.mp.model.jooq.tables;


import com.mp.model.jooq.Keys;
import com.mp.model.jooq.Testdb;
import com.mp.model.jooq.tables.records.InfUserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InfUser extends TableImpl<InfUserRecord> {

    private static final long serialVersionUID = 752243924;

    /**
     * The reference instance of <code>testdb.inf_user</code>
     */
    public static final InfUser INF_USER = new InfUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InfUserRecord> getRecordType() {
        return InfUserRecord.class;
    }

    /**
     * The column <code>testdb.inf_user.user_id</code>.
     */
    public final TableField<InfUserRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.CHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>testdb.inf_user.user_name</code>.
     */
    public final TableField<InfUserRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>testdb.inf_user.nick_name</code>.
     */
    public final TableField<InfUserRecord, String> NICK_NAME = createField("nick_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>testdb.inf_user.first_name</code>.
     */
    public final TableField<InfUserRecord, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>testdb.inf_user.last_name</code>.
     */
    public final TableField<InfUserRecord, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>testdb.inf_user.email</code>.
     */
    public final TableField<InfUserRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>testdb.inf_user.mobile_number</code>.
     */
    public final TableField<InfUserRecord, String> MOBILE_NUMBER = createField("mobile_number", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>testdb.inf_user</code> table reference
     */
    public InfUser() {
        this("inf_user", null);
    }

    /**
     * Create an aliased <code>testdb.inf_user</code> table reference
     */
    public InfUser(String alias) {
        this(alias, INF_USER);
    }

    private InfUser(String alias, Table<InfUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private InfUser(String alias, Table<InfUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Testdb.TESTDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InfUserRecord> getPrimaryKey() {
        return Keys.KEY_INF_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InfUserRecord>> getKeys() {
        return Arrays.<UniqueKey<InfUserRecord>>asList(Keys.KEY_INF_USER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InfUser as(String alias) {
        return new InfUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InfUser rename(String name) {
        return new InfUser(name, null);
    }
}
