spring:
  profiles:
    active: development
    #active: test
    #active: production

  server:
    port: 8080
  
  local:
    server:
      port: 8080
  
  # 数据库及相关中间件的配置
  jooq:
    sql-dialect: MYSQL
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    username: test
    password: test

    initialize: false
    hikari:
      # 自定义数据连接池的名字
      poolName: HikariCP-TestDB
      # 从连接池获取数据库连接的超时时间。
      # Lowest acceptable connection timeout is 250 ms. Default: 30000 (30 seconds)
      connectionTimeout: 10000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maxLifetime: 1765000 
      # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximumPoolSize: 10
      # 连接池中保持的最小连接数。
      # Default: same as maximumPoolSize
      minimumIdle: 2
      # 一个连接的空闲时间（毫秒），超过则被释放。
      # This setting only applies when minimumIdle is defined to be less than maximumPoolSize. 
      # The minimum allowed value is 10000ms (10 seconds). Default: 600000 (10 minutes)
      idleTimeout: 300000

      # MySql特有DataSource配置
      # 参考http://assets.en.oreilly.com/1/event/21/Connector_J%20Performance%20Gems%20Presentation.pdf
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 204
      useServerPrepStmts: true
      useLocalSessionState: true
      useLocalTransactionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false

---
# 开发环境配置
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/testdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull

---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/testdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  
---
# 生产环境配置
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/testdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull