/*
 * This file is generated by jOOQ.
*/
package com.mp.model.jooq.tables.daos;


import com.mp.model.jooq.tables.InfUser;
import com.mp.model.jooq.tables.records.InfUserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class InfUserDao extends DAOImpl<InfUserRecord, com.mp.model.jooq.tables.pojos.InfUser, String> {

    /**
     * Create a new InfUserDao without any configuration
     */
    public InfUserDao() {
        super(InfUser.INF_USER, com.mp.model.jooq.tables.pojos.InfUser.class);
    }

    /**
     * Create a new InfUserDao with an attached configuration
     */
    @Autowired
    public InfUserDao(Configuration configuration) {
        super(InfUser.INF_USER, com.mp.model.jooq.tables.pojos.InfUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mp.model.jooq.tables.pojos.InfUser object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.InfUser> fetchByUserId(String... values) {
        return fetch(InfUser.INF_USER.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.mp.model.jooq.tables.pojos.InfUser fetchOneByUserId(String value) {
        return fetchOne(InfUser.INF_USER.USER_ID, value);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.InfUser> fetchByUserName(String... values) {
        return fetch(InfUser.INF_USER.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>nick_name IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.InfUser> fetchByNickName(String... values) {
        return fetch(InfUser.INF_USER.NICK_NAME, values);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.InfUser> fetchByFirstName(String... values) {
        return fetch(InfUser.INF_USER.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.InfUser> fetchByLastName(String... values) {
        return fetch(InfUser.INF_USER.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.InfUser> fetchByEmail(String... values) {
        return fetch(InfUser.INF_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>mobile_number IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.InfUser> fetchByMobileNumber(String... values) {
        return fetch(InfUser.INF_USER.MOBILE_NUMBER, values);
    }
}
