/*
 * This file is generated by jOOQ.
*/
package com.mp.model.jooq.tables.daos;


import com.mp.model.jooq.tables.SysAuthentication;
import com.mp.model.jooq.tables.records.SysAuthenticationRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAuthenticationDao extends DAOImpl<SysAuthenticationRecord, com.mp.model.jooq.tables.pojos.SysAuthentication, Integer> {

    /**
     * Create a new SysAuthenticationDao without any configuration
     */
    public SysAuthenticationDao() {
        super(SysAuthentication.SYS_AUTHENTICATION, com.mp.model.jooq.tables.pojos.SysAuthentication.class);
    }

    /**
     * Create a new SysAuthenticationDao with an attached configuration
     */
    public SysAuthenticationDao(Configuration configuration) {
        super(SysAuthentication.SYS_AUTHENTICATION, com.mp.model.jooq.tables.pojos.SysAuthentication.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.mp.model.jooq.tables.pojos.SysAuthentication object) {
        return object.getAuthId();
    }

    /**
     * Fetch records that have <code>auth_id IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.SysAuthentication> fetchByAuthId(Integer... values) {
        return fetch(SysAuthentication.SYS_AUTHENTICATION.AUTH_ID, values);
    }

    /**
     * Fetch a unique record that has <code>auth_id = value</code>
     */
    public com.mp.model.jooq.tables.pojos.SysAuthentication fetchOneByAuthId(Integer value) {
        return fetchOne(SysAuthentication.SYS_AUTHENTICATION.AUTH_ID, value);
    }

    /**
     * Fetch records that have <code>auth_code IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.SysAuthentication> fetchByAuthCode(String... values) {
        return fetch(SysAuthentication.SYS_AUTHENTICATION.AUTH_CODE, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.mp.model.jooq.tables.pojos.SysAuthentication> fetchByPassword(String... values) {
        return fetch(SysAuthentication.SYS_AUTHENTICATION.PASSWORD, values);
    }
}
