/*
 * This file is generated by jOOQ.
*/
package com.mp.model.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IInfUser extends Serializable {

    /**
     * Setter for <code>testdb.inf_user.user_id</code>.
     */
    public void setUserId(Integer value);

    /**
     * Getter for <code>testdb.inf_user.user_id</code>.
     */
    public Integer getUserId();

    /**
     * Setter for <code>testdb.inf_user.user_name</code>.
     */
    public void setUserName(String value);

    /**
     * Getter for <code>testdb.inf_user.user_name</code>.
     */
    public String getUserName();

    /**
     * Setter for <code>testdb.inf_user.nick_name</code>.
     */
    public void setNickName(String value);

    /**
     * Getter for <code>testdb.inf_user.nick_name</code>.
     */
    public String getNickName();

    /**
     * Setter for <code>testdb.inf_user.first_name</code>.
     */
    public void setFirstName(String value);

    /**
     * Getter for <code>testdb.inf_user.first_name</code>.
     */
    public String getFirstName();

    /**
     * Setter for <code>testdb.inf_user.last_name</code>.
     */
    public void setLastName(String value);

    /**
     * Getter for <code>testdb.inf_user.last_name</code>.
     */
    public String getLastName();

    /**
     * Setter for <code>testdb.inf_user.email</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>testdb.inf_user.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>testdb.inf_user.mobile_number</code>.
     */
    public void setMobileNumber(String value);

    /**
     * Getter for <code>testdb.inf_user.mobile_number</code>.
     */
    public String getMobileNumber();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IInfUser
     */
    public void from(com.mp.model.jooq.tables.interfaces.IInfUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IInfUser
     */
    public <E extends com.mp.model.jooq.tables.interfaces.IInfUser> E into(E into);
}
