/*
 * This file is generated by jOOQ.
*/
package com.mp.model.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISysAuthentication extends Serializable {

    /**
     * Setter for <code>testdb.sys_authentication.auth_id</code>.
     */
    public void setAuthId(Integer value);

    /**
     * Getter for <code>testdb.sys_authentication.auth_id</code>.
     */
    public Integer getAuthId();

    /**
     * Setter for <code>testdb.sys_authentication.auth_code</code>.
     */
    public void setAuthCode(String value);

    /**
     * Getter for <code>testdb.sys_authentication.auth_code</code>.
     */
    public String getAuthCode();

    /**
     * Setter for <code>testdb.sys_authentication.password</code>.
     */
    public void setPassword(String value);

    /**
     * Getter for <code>testdb.sys_authentication.password</code>.
     */
    public String getPassword();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISysAuthentication
     */
    public void from(com.mp.model.jooq.tables.interfaces.ISysAuthentication from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISysAuthentication
     */
    public <E extends com.mp.model.jooq.tables.interfaces.ISysAuthentication> E into(E into);
}
