/*
 * This file is generated by jOOQ.
*/
package com.mp.model.jooq;


import com.mp.model.jooq.tables.InfUser;
import com.mp.model.jooq.tables.SysAuthentication;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Testdb extends SchemaImpl {

    private static final long serialVersionUID = -990431753;

    /**
     * The reference instance of <code>testdb</code>
     */
    public static final Testdb TESTDB = new Testdb();

    /**
     * The table <code>testdb.inf_user</code>.
     */
    public final InfUser INF_USER = com.mp.model.jooq.tables.InfUser.INF_USER;

    /**
     * The table <code>testdb.sys_authentication</code>.
     */
    public final SysAuthentication SYS_AUTHENTICATION = com.mp.model.jooq.tables.SysAuthentication.SYS_AUTHENTICATION;

    /**
     * No further instances allowed
     */
    private Testdb() {
        super("testdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            InfUser.INF_USER,
            SysAuthentication.SYS_AUTHENTICATION);
    }
}
