/*
 * This file is generated by jOOQ.
*/
package com.mp.model.jooq.tables.pojos;


import com.mp.model.jooq.tables.interfaces.ISysAuthentication;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAuthentication implements ISysAuthentication {

    private static final long serialVersionUID = -768695646;

    private Integer authId;
    private String  authCode;
    private String  password;

    public SysAuthentication() {}

    public SysAuthentication(SysAuthentication value) {
        this.authId = value.authId;
        this.authCode = value.authCode;
        this.password = value.password;
    }

    public SysAuthentication(
        Integer authId,
        String  authCode,
        String  password
    ) {
        this.authId = authId;
        this.authCode = authCode;
        this.password = password;
    }

    @Override
    public Integer getAuthId() {
        return this.authId;
    }

    @Override
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }

    @Override
    public String getAuthCode() {
        return this.authCode;
    }

    @Override
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SysAuthentication other = (SysAuthentication) obj;
        if (authId == null) {
            if (other.authId != null)
                return false;
        }
        else if (!authId.equals(other.authId))
            return false;
        if (authCode == null) {
            if (other.authCode != null)
                return false;
        }
        else if (!authCode.equals(other.authCode))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((authId == null) ? 0 : authId.hashCode());
        result = prime * result + ((authCode == null) ? 0 : authCode.hashCode());
        result = prime * result + ((password == null) ? 0 : password.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysAuthentication (");

        sb.append(authId);
        sb.append(", ").append(authCode);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISysAuthentication from) {
        setAuthId(from.getAuthId());
        setAuthCode(from.getAuthCode());
        setPassword(from.getPassword());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISysAuthentication> E into(E into) {
        into.from(this);
        return into;
    }
}
